### ISSUE TITLE
Does the Google Consumer Surveys API still exist?

### ISSUE THREAD

**Issue by jeanfw** [google/consumer-surveys#2]
I can't find it in the Google Developers Console:

<img width="491" alt="screen shot 2016-01-27 at 10 36 00" src="https://cloud.githubusercontent.com/assets/2714769/12609417/d5a11cfc-c4e1-11e5-8ec8-23831ffe0054.png">

How can I get access ? 

Thanks !

**Comment by edylan** [comment]
Hi Jean, thanks for checking in on this. The Consumer Surveys API is currently enabled for a subset of our Enterprise customers today. If you think you'd like to test it and have a good business use for it, then feel free to fill out the form @ https://goo.gl/hwxHHm and we'll be in touch.

Cheers,
Dylan Lorimer
