### ISSUE TITLE
Missing a file

### ISSUE THREAD

**Issue by subkanthi** [google/consumer-surveys#5]
It seems to be missing the SurveyQuestionImage file?

**Comment by AngryBrock** [comment]
Strange, it does look like this is missing.
https://github.com/google/consumer-surveys/blob/master/java/com/google/api/services/consumersurveys/model/SurveyQuestion.java#L69

@stevededalus any idea why this is happening?

**Comment by stevededalus** [comment]
I'll look into this and have an update by Monday.

**Comment by stevededalus** [comment]
Thanks for pointing this out @subkanthi, I've pushed a new version of the library now that contains the missing file.
